"""Constants."""
# Global
APP_NAME = "Chess Tournament Manager"

UPDATE_TOURNAMENT_PROMPT = "O"
UPDATE_PLAYERS_LIST_PROMPT = "O"

# Tournament
NUMBER_OF_PLAYERS = 8
DEFAULT_NUMBER_OF_ROUNDS = 4
TIME_CONTROL_BLITZ = 0
TIME_CONTROL_BULLET = 1
TIME_CONTROL_RAPID = 2

TIME_CONTROL_BLITZ_PROMPT = "BL"
TIME_CONTROL_BULLET_PROMPT = "BU"
TIME_CONTROL_RAPID_PROMPT = "R"

# Player
PLAYERS_LAST_NAMES = ["DUPONT", "DUPUIS", "JOHNSON", "KAPOOR", "KHAN", "KLEIN",
                      "MARTIN", "PEREZ", "QUENTIN", "ROBERT", "THIERRY", "THOMAS"]
PLAYERS_FIRST_NAMES = ["Alex", "Camille", "Charlie", "Dominique", "Fred", "Gwen",
                       "Joe", "Johnny", "Jordan", "Lauren", "Max", "Sam"]
PLAYERS_BIRTH_DATES = ["03/08/1995", "25/02/2000", "09/12/1987", "10/10/1996", "02/07/1998", "13/07/2002", "22/09/1990"]
GENDER_M = 0
GENDER_F = 1
GENDERS = [GENDER_M, GENDER_F]

# Round
FIRST_ROUND_ID = 0

# Match
WIN_SCORE = 1.0
LOSE_SCORE = 0
DRAW_SCORE = 0.5

WIN_PROMPT = "V"
LOSE_PROMPT = "D"
DRAW_PROMPT = "N"

SEPARATOR_TYPE = "#"
SEPARATOR = SEPARATOR_TYPE * 79
