"""Constants."""
# GLOBAL
APP_NAME = "Chess Tournament Manager"

MENU_STATE = 0
MANAGE_TOURNAMENT_STATE = 1
MANAGE_PLAYERS_LIST_STATE = 2
RUN_TOURNAMENT_STATE = 3
LOAD_REPORT_STATE = 4
SHOW_REPORT_STATE = 5
QUIT_STATE = "Q"
BASIC_STATES = [MENU_STATE, MANAGE_TOURNAMENT_STATE, MANAGE_PLAYERS_LIST_STATE,
                RUN_TOURNAMENT_STATE, LOAD_REPORT_STATE]

SEPARATOR_TYPE = "#"
SEPARATOR = SEPARATOR_TYPE * 79

UPDATE_TOURNAMENT_PROMPT = "O"
UPDATE_PLAYERS_LIST_PROMPT = "O"
SAVE_RESULTS_PROMPT = "O"

# MODELS
# Tournament
NUMBER_OF_PLAYERS = 8
DEFAULT_NUMBER_OF_ROUNDS = 4
TIME_CONTROL_BLITZ = 0
TIME_CONTROL_BULLET = 1
TIME_CONTROL_RAPID = 2

TIME_CONTROL_BLITZ_PROMPT = "BL"
TIME_CONTROL_BULLET_PROMPT = "BU"
TIME_CONTROL_RAPID_PROMPT = "R"

# Player
GENDER_M = 0
GENDER_W = 1

GENDER_M_PROMPT = "H"
GENDER_W_PROMPT = "F"

# Round
FIRST_ROUND_ID = 1
BEGINNING_PLAYED_ROUNDS_NUMBER = 0

CONTINUE_NEXT_ROUND_FALSE_PROMPT = "N"

# Match
WIN_SCORE = 1.0
LOSE_SCORE = 0
DRAW_SCORE = 0.5

WIN_PROMPT = "V"
LOSE_PROMPT = "D"
DRAW_PROMPT = "N"

# DATABASE
# Global
DB_NAME = "db.json"
REPORT_DB_NAME = "results.json"

# Tables
DB_TABLE_TOURNAMENT = "tournament"
DB_TABLE_PLAYERS = "players"
DB_TABLE_ROUNDS = "rounds"

# Tournament table
DB_TOURNAMENT_NAME = "name"
DB_TOURNAMENT_PLACE = "place"
DB_TOURNAMENT_DATE = "date"
DB_TOURNAMENT_TIME_CONTROL = "time_control"
DB_TOURNAMENT_DESCRIPTION = "description"
DB_TOURNAMENT_NUMBER_OF_ROUNDS = "number_of_rounds"
DB_TOURNAMENT_PLAYED_ROUNDS = "played_rounds"

# Player table
DB_PLAYER_ID = "id"
DB_PLAYER_LAST_NAME = "last_name"
DB_PLAYER_FIRST_NAME = "first_name"
DB_PLAYER_DATE_OF_BIRTH = "date_of_birth"
DB_PLAYER_GENDER = "gender"
DB_PLAYER_RANK = "rank"

# Round table
DB_ROUND_ID = "id"
DB_ROUND_NAME = "name"
DB_ROUND_BEGINNING_TIME = "beginning_time"
DB_ROUND_ENDING_TIME = "ending_time"
DB_ROUND_MATCHES_LIST = "matches"

# Match inside round
DB_MATCH_FIRST_PLAYER_ID = "first_player_id"
DB_MATCH_FIRST_PLAYER_SCORE = "first_player_score"
DB_MATCH_SECOND_PLAYER_ID = "second_player_id"
DB_MATCH_SECOND_PLAYER_SCORE = "second_player_score"

# REPORTS
SHOW_PLAYERS_ALPHABETIC_PROMPT = 1
SHOW_PLAYERS_RANK_PROMPT = 2
SHOW_PLAYERS_SCORE_PROMPT = 3
SHOW_ROUNDS_LIST_PROMPT = 4
SHOW_MATCHES_LIST_PROMPT = 5
SHOW_REPORT_CHOICES = [SHOW_PLAYERS_ALPHABETIC_PROMPT, SHOW_PLAYERS_RANK_PROMPT,
                       SHOW_PLAYERS_SCORE_PROMPT, SHOW_ROUNDS_LIST_PROMPT,
                       SHOW_MATCHES_LIST_PROMPT]

SORT_BY_NAME = 0
SORT_BY_RANK = 1
SORT_BY_SCORE = 2
